services:
  warehouse-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse-api
    restart: unless-stopped

    depends_on:
      - warehouse-postgres
      - warehouse-redis

    ports:
      - "${APP_PORT}:${APP_PORT}"

    # Load env cho app
    env_file:
      - .env.pro

    networks:
      - warehouse-net

    # Tối ưu bảo mật
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true

  warehouse-redis:
    image: redis:7-alpine
    container_name: warehouse-redis
    restart: unless-stopped

    command: ["redis-server", "--appendonly", "yes"]

    volumes:
      - warehouse_redis_data:/data

    networks:
      - warehouse-net

    expose:
      - "6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10

  warehouse-postgres:
    image: postgres:16-alpine
    container_name: warehouse-postgres
    restart: unless-stopped

    # Load env cho postgres (POSTGRES_DB/USER/PASSWORD)
    env_file:
      - .env.pro

    volumes:
      - warehouse_pg_data:/var/lib/postgresql/data

    networks:
      - warehouse-net

    expose:
      - "5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  warehouse-net:
    driver: bridge

volumes:
  warehouse_pg_data:
  warehouse_redis_data:
